---
delimiters:
    - "__"
constantDelimiters:
    - "$$"
ignore:
    - "config.yml"
    - ".DS_Store"
    - ".git"
    - "node_modules"
    - ".env"
rootDirectoryName: "$$project root directory name$$"